---
apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: {{NAMESPACE}}-rabbitmq

build:
  artifacts: []

deploy:
  kubeContext: minikube
  helm:
    releases:
      - name: rabbitmq
        remoteChart: bitnami/rabbitmq
        namespace: {{NAMESPACE}}
        valuesFiles:
          - helm.values.yaml

portForward:
  - resourceType: service
    resourceName: rabbitmq
    namespace: {{NAMESPACE}}
    port: 5672
    localPort: 5672
  - resourceType: service
    resourceName: rabbitmq
    namespace: {{NAMESPACE}}
    port: 15672
    localPort: 15672