---
apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: {{NAMESPACE}}-mongodb

build:
  artifacts: []

deploy:
  kubeContext: minikube
  helm:
    releases:
      - name: mongodb
        remoteChart: bitnami/mongodb
        namespace: {{NAMESPACE}}
        valuesFiles:
          - helm.values.yaml

portForward:
  - resourceType: service
    resourceName: mongodb
    namespace: {{NAMESPACE}}
    port: 27017
    localPort: 27017