##  Full configuration lives here: https://github.com/bitnami/charts/blob/main/bitnami/elasticsearch/values.yaml

global:
  kibanaEnabled: true

security:
  enabled: false

kibana:
  elasticsearch:
    security:
      auth:
        enabled: false

master:
  masterOnly: false
  replicaCount: 1

data:
  replicaCount: 0

coordinating:
  replicaCount: 0

ingest:
  replicaCount: 0
