---
apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: {{NAMESPACE}}-mariadb

build:
  artifacts: []

deploy:
  kubeContext: minikube
  helm:
    releases:
      - name: mariadb
        remoteChart: bitnami/mariadb
        namespace: {{NAMESPACE}}
        valuesFiles:
          - helm.values.yaml

portForward:
  - resourceType: service
    resourceName: mariadb
    namespace: {{NAMESPACE}}
    port: 3306
    localPort: 3306