## Full configuration lives here: https://github.com/bitnami/charts/blob/main/bitnami/redis/values.yaml

architecture: replication

auth:
  existingSecret: secrets-pass
  existingSecretPasswordKey: redis-password
  enabled: true
  sentinel: true

rbac:
  create: true

serviceAccount:
  create: true
  automountServiceAccountToken: true

master:
  automountServiceAccountToken: true
  persistence:
    enabled: true
    size: 1Gi

replica:
  automountServiceAccountToken: true

sentinel:
  enabled: true
  count: 2
  quorum: 2
  service:
    createMaster: true
  externalMaster:
    enabled: true
  resourcesPreset: nano
