##  Full configuration lives here: https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
architecture: standalone

auth:
  username: {{DEFAULT_USER}}
  database: app
  existingSecret: "secrets-pass"
  secretKeys:
    adminPasswordKey: postgres-admin-password
    userPasswordKey: postgres-user-password
    replicationPasswordKey: postgres-replication-password