---
apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: {{NAMESPACE}}-postgresql

build:
  artifacts: []

deploy:
  kubeContext: minikube
  helm:
    releases:
      - name: postgresql
        remoteChart: bitnami/postgresql
        namespace: {{NAMESPACE}}
        valuesFiles:
          - helm.values.yaml

portForward:
  - resourceType: service
    resourceName: postgresql
    namespace: {{NAMESPACE}}
    port: 5432
    localPort: 5432