## Full configuration lives here: https://github.com/provectus/kafka-ui-charts/blob/main/charts/kafka-ui/values.yaml

replicaCount: 1

image:
  repository: provectuslabs/kafka-ui
  pullPolicy: IfNotPresent
  tag: latest

yamlApplicationConfig:
  kafka:
    clusters:
      - name: kafka-cluster
        bootstrapServers: kafka-cluster:9092
  management:
    health:
      ldap:
        enabled: false
  auth:
    type: disabled

env:
  - { name: DYNAMIC_CONFIG_ENABLED, value: 'true' }
