---
apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: {{NAMESPACE}}-kafka

build:
  artifacts: []

deploy:
  kubeContext: minikube
  helm:
    releases:
      - name: kafka-cluster
        remoteChart: bitnami/kafka
        namespace: {{NAMESPACE}}
        valuesFiles:
          - helm.values.yaml
      - name: kafka-ui
        remoteChart: kafka-ui/kafka-ui
        namespace: {{NAMESPACE}}
        valuesFiles:
          - helm.ui.values.yaml

portForward:
  - resourceType: service
    resourceName: kafka-ui
    namespace: {{NAMESPACE}}
    port: 80
    localPort: 9092