---
apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: {{NAMESPACE}}-cockroachdb

build:
  artifacts: []

deploy:
  kubeContext: minikube
  helm:
    releases:
      - name: cockroachdb
        remoteChart: cockroachdb/cockroachdb
        namespace: {{NAMESPACE}}
        valuesFiles:
          - helm.values.yaml

portForward:
  - resourceType: service
    resourceName: cockroachdb
    namespace: {{NAMESPACE}}
    port: 8080
    localPort: 26257