---
apiVersion: skaffold/v4beta11
kind: Config

profiles:
  - name: local
    activation:
     - kubeContext: minikube
    manifests:
      rawYaml:
        - namespace.yaml
        - service-account.yaml
        - cluster-role.yaml
        - cluster-role-binding.yaml
        - secrets.yaml
        - secrets.pass.yaml
    deploy:
      kubectl:
        defaultNamespace: {{NAMESPACE}}
      kubeContext: minikube